/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ServiceType = IDL.Variant({
  'lTLTruckLoad' : IDL.Null,
  'fullTruckLoad' : IDL.Null,
  'customizedLogistic' : IDL.Null,
});
export const QuoteRequestInput = IDL.Record({
  'to' : IDL.Text,
  'serviceType' : ServiceType,
  'from' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const QuoteRequest = IDL.Record({
  'id' : IDL.Nat,
  'to' : IDL.Text,
  'serviceType' : ServiceType,
  'from' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'timestampNanos' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAllQuotes' : IDL.Func([], [], []),
  'deleteQuoteRequest' : IDL.Func([IDL.Nat], [], []),
  'deleteQuotesByEmail' : IDL.Func([IDL.Text], [], []),
  'editQuote' : IDL.Func([IDL.Nat, QuoteRequestInput], [], []),
  'filterQuotesByDestinationCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'filterQuotesByOriginCity' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'filterQuotesByServiceType' : IDL.Func(
      [ServiceType],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'getAllQuoteRequestsSorted' : IDL.Func(
      [],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuoteCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getQuoteRequests' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'getQuoteRequestsInTimeRange' : IDL.Func(
      [IDL.Int, IDL.Int],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'getQuotesForEmail' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'getTopRecentQuotesByTimestamp' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'searchQuotesForTerm' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(QuoteRequest)],
      ['query'],
    ),
  'submitQuote' : IDL.Func([QuoteRequestInput], [IDL.Nat], []),
  'updateServiceType' : IDL.Func([IDL.Nat, ServiceType], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ServiceType = IDL.Variant({
    'lTLTruckLoad' : IDL.Null,
    'fullTruckLoad' : IDL.Null,
    'customizedLogistic' : IDL.Null,
  });
  const QuoteRequestInput = IDL.Record({
    'to' : IDL.Text,
    'serviceType' : ServiceType,
    'from' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const QuoteRequest = IDL.Record({
    'id' : IDL.Nat,
    'to' : IDL.Text,
    'serviceType' : ServiceType,
    'from' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'timestampNanos' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAllQuotes' : IDL.Func([], [], []),
    'deleteQuoteRequest' : IDL.Func([IDL.Nat], [], []),
    'deleteQuotesByEmail' : IDL.Func([IDL.Text], [], []),
    'editQuote' : IDL.Func([IDL.Nat, QuoteRequestInput], [], []),
    'filterQuotesByDestinationCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'filterQuotesByOriginCity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'filterQuotesByServiceType' : IDL.Func(
        [ServiceType],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'getAllQuoteRequestsSorted' : IDL.Func(
        [],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuoteCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getQuoteRequests' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'getQuoteRequestsInTimeRange' : IDL.Func(
        [IDL.Int, IDL.Int],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'getQuotesForEmail' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'getTopRecentQuotesByTimestamp' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'searchQuotesForTerm' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(QuoteRequest)],
        ['query'],
      ),
    'submitQuote' : IDL.Func([QuoteRequestInput], [IDL.Nat], []),
    'updateServiceType' : IDL.Func([IDL.Nat, ServiceType], [], []),
  });
};

export const init = ({ IDL }) => { return []; };