/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface QuoteRequest {
  'id' : bigint,
  'to' : string,
  'serviceType' : ServiceType,
  'from' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'timestampNanos' : bigint,
}
export interface QuoteRequestInput {
  'to' : string,
  'serviceType' : ServiceType,
  'from' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export type ServiceType = { 'lTLTruckLoad' : null } |
  { 'fullTruckLoad' : null } |
  { 'customizedLogistic' : null };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAllQuotes' : ActorMethod<[], undefined>,
  'deleteQuoteRequest' : ActorMethod<[bigint], undefined>,
  'deleteQuotesByEmail' : ActorMethod<[string], undefined>,
  'editQuote' : ActorMethod<[bigint, QuoteRequestInput], undefined>,
  'filterQuotesByDestinationCity' : ActorMethod<[string], Array<QuoteRequest>>,
  'filterQuotesByOriginCity' : ActorMethod<[string], Array<QuoteRequest>>,
  'filterQuotesByServiceType' : ActorMethod<[ServiceType], Array<QuoteRequest>>,
  'getAllQuoteRequestsSorted' : ActorMethod<[], Array<QuoteRequest>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getQuoteCount' : ActorMethod<[], bigint>,
  'getQuoteRequests' : ActorMethod<[bigint, bigint], Array<QuoteRequest>>,
  'getQuoteRequestsInTimeRange' : ActorMethod<
    [bigint, bigint],
    Array<QuoteRequest>
  >,
  'getQuotesForEmail' : ActorMethod<[string], Array<QuoteRequest>>,
  'getTopRecentQuotesByTimestamp' : ActorMethod<[bigint], Array<QuoteRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'searchQuotesForTerm' : ActorMethod<[string], Array<QuoteRequest>>,
  'submitQuote' : ActorMethod<[QuoteRequestInput], bigint>,
  'updateServiceType' : ActorMethod<[bigint, ServiceType], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];