/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface QuoteRequestInput {
    to: string;
    serviceType: ServiceType;
    from: string;
    name: string;
    email: string;
    message: string;
    phone: string;
}
export interface QuoteRequest {
    id: bigint;
    to: string;
    serviceType: ServiceType;
    from: string;
    name: string;
    email: string;
    message: string;
    phone: string;
    timestampNanos: bigint;
}
export enum ServiceType {
    lTLTruckLoad = "lTLTruckLoad",
    fullTruckLoad = "fullTruckLoad",
    customizedLogistic = "customizedLogistic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAllQuotes(): Promise<void>;
    deleteQuoteRequest(id: bigint): Promise<void>;
    deleteQuotesByEmail(email: string): Promise<void>;
    editQuote(id: bigint, input: QuoteRequestInput): Promise<void>;
    filterQuotesByDestinationCity(destinationCity: string): Promise<Array<QuoteRequest>>;
    filterQuotesByOriginCity(originCity: string): Promise<Array<QuoteRequest>>;
    filterQuotesByServiceType(serviceType: ServiceType): Promise<Array<QuoteRequest>>;
    getAllQuoteRequestsSorted(): Promise<Array<QuoteRequest>>;
    getCallerUserRole(): Promise<UserRole>;
    getQuoteCount(): Promise<bigint>;
    getQuoteRequests(pageSize: bigint, pageIndex: bigint): Promise<Array<QuoteRequest>>;
    getQuoteRequestsInTimeRange(startTimeNanos: bigint, endTimeNanos: bigint): Promise<Array<QuoteRequest>>;
    getQuotesForEmail(email: string): Promise<Array<QuoteRequest>>;
    getTopRecentQuotesByTimestamp(count: bigint): Promise<Array<QuoteRequest>>;
    isCallerAdmin(): Promise<boolean>;
    searchQuotesForTerm(term: string): Promise<Array<QuoteRequest>>;
    submitQuote(input: QuoteRequestInput): Promise<bigint>;
    updateServiceType(id: bigint, serviceType: ServiceType): Promise<void>;
}
import type { QuoteRequest as _QuoteRequest, QuoteRequestInput as _QuoteRequestInput, ServiceType as _ServiceType, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAllQuotes(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllQuotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllQuotes();
            return result;
        }
    }
    async deleteQuoteRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuoteRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuoteRequest(arg0);
            return result;
        }
    }
    async deleteQuotesByEmail(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQuotesByEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQuotesByEmail(arg0);
            return result;
        }
    }
    async editQuote(arg0: bigint, arg1: QuoteRequestInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editQuote(arg0, to_candid_QuoteRequestInput_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editQuote(arg0, to_candid_QuoteRequestInput_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async filterQuotesByDestinationCity(arg0: string): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterQuotesByDestinationCity(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterQuotesByDestinationCity(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterQuotesByOriginCity(arg0: string): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterQuotesByOriginCity(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterQuotesByOriginCity(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterQuotesByServiceType(arg0: ServiceType): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterQuotesByServiceType(to_candid_ServiceType_n5(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterQuotesByServiceType(to_candid_ServiceType_n5(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllQuoteRequestsSorted(): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuoteRequestsSorted();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuoteRequestsSorted();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuoteCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuoteCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuoteCount();
            return result;
        }
    }
    async getQuoteRequests(arg0: bigint, arg1: bigint): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuoteRequests(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuoteRequests(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuoteRequestsInTimeRange(arg0: bigint, arg1: bigint): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuoteRequestsInTimeRange(arg0, arg1);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuoteRequestsInTimeRange(arg0, arg1);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getQuotesForEmail(arg0: string): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotesForEmail(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotesForEmail(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopRecentQuotesByTimestamp(arg0: bigint): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopRecentQuotesByTimestamp(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopRecentQuotesByTimestamp(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async searchQuotesForTerm(arg0: string): Promise<Array<QuoteRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchQuotesForTerm(arg0);
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchQuotesForTerm(arg0);
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitQuote(arg0: QuoteRequestInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitQuote(to_candid_QuoteRequestInput_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitQuote(to_candid_QuoteRequestInput_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateServiceType(arg0: bigint, arg1: ServiceType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceType(arg0, to_candid_ServiceType_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceType(arg0, to_candid_ServiceType_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_QuoteRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QuoteRequest): QuoteRequest {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceType): ServiceType {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    to: string;
    serviceType: _ServiceType;
    from: string;
    name: string;
    email: string;
    message: string;
    phone: string;
    timestampNanos: bigint;
}): {
    id: bigint;
    to: string;
    serviceType: ServiceType;
    from: string;
    name: string;
    email: string;
    message: string;
    phone: string;
    timestampNanos: bigint;
} {
    return {
        id: value.id,
        to: value.to,
        serviceType: from_candid_ServiceType_n10(_uploadFile, _downloadFile, value.serviceType),
        from: value.from,
        name: value.name,
        email: value.email,
        message: value.message,
        phone: value.phone,
        timestampNanos: value.timestampNanos
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lTLTruckLoad: null;
} | {
    fullTruckLoad: null;
} | {
    customizedLogistic: null;
}): ServiceType {
    return "lTLTruckLoad" in value ? ServiceType.lTLTruckLoad : "fullTruckLoad" in value ? ServiceType.fullTruckLoad : "customizedLogistic" in value ? ServiceType.customizedLogistic : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_QuoteRequest>): Array<QuoteRequest> {
    return value.map((x)=>from_candid_QuoteRequest_n8(_uploadFile, _downloadFile, x));
}
function to_candid_QuoteRequestInput_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QuoteRequestInput): _QuoteRequestInput {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_ServiceType_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): _ServiceType {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    to: string;
    serviceType: ServiceType;
    from: string;
    name: string;
    email: string;
    message: string;
    phone: string;
}): {
    to: string;
    serviceType: _ServiceType;
    from: string;
    name: string;
    email: string;
    message: string;
    phone: string;
} {
    return {
        to: value.to,
        serviceType: to_candid_ServiceType_n5(_uploadFile, _downloadFile, value.serviceType),
        from: value.from,
        name: value.name,
        email: value.email,
        message: value.message,
        phone: value.phone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ServiceType): {
    lTLTruckLoad: null;
} | {
    fullTruckLoad: null;
} | {
    customizedLogistic: null;
} {
    return value == ServiceType.lTLTruckLoad ? {
        lTLTruckLoad: null
    } : value == ServiceType.fullTruckLoad ? {
        fullTruckLoad: null
    } : value == ServiceType.customizedLogistic ? {
        customizedLogistic: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
